// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtVHMDp-O7py2xrwA4V1XTj9oxTZ6PPtI',
    appId: '1:1056183951157:web:fac5629867d756b8b6367c',
    messagingSenderId: '1056183951157',
    projectId: 'photogallery-dfcf2',
    authDomain: 'photogallery-dfcf2.firebaseapp.com',
    storageBucket: 'photogallery-dfcf2.appspot.com',
    measurementId: 'G-TRQ8624VED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJnriew7Pn4yOo3gtvpU_aL1DSjUies8',
    appId: '1:1056183951157:android:1933b7b7faa7a474b6367c',
    messagingSenderId: '1056183951157',
    projectId: 'photogallery-dfcf2',
    storageBucket: 'photogallery-dfcf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_XdvohLjgUG0PPtZx43JPrIo5cyH4iLQ',
    appId: '1:1056183951157:ios:e5c31553087fa8f6b6367c',
    messagingSenderId: '1056183951157',
    projectId: 'photogallery-dfcf2',
    storageBucket: 'photogallery-dfcf2.appspot.com',
    iosBundleId: 'com.example.unsplashedPhotoGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_XdvohLjgUG0PPtZx43JPrIo5cyH4iLQ',
    appId: '1:1056183951157:ios:12c5c6901990f512b6367c',
    messagingSenderId: '1056183951157',
    projectId: 'photogallery-dfcf2',
    storageBucket: 'photogallery-dfcf2.appspot.com',
    iosBundleId: 'com.example.unsplashedPhotoGallery.RunnerTests',
  );
}
